; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.x"

; Modules
projects[amazon][version] = "1.4"

projects[views_bulk_operations][version] = "1.12"

projects[active_tags][version] = "1.9"

projects[admin_menu][version] = "1.8"

projects[adsense][version] = "1.4"

projects[advanced_help][version] = "1.2"

projects[auto_nodetitle][version] = "1.2"

projects[backup_migrate][version] = "2.4"

projects[backup_migrate_files][version] = "1.x-dev"

projects[better_exposed_filters][version] = "3.0-beta1"

projects[better_formats][version] = "1.2"

projects[betterselect][version] = "1.0-beta3"

projects[ctools][version] = "1.9"

projects[ckeditor_link][version] = "2.2"

projects[cck][version] = "3.0-alpha3"

projects[content_taxonomy][version] = "1.0-rc2"

projects[cnr][version] = "4.1"

projects[date][version] = "2.8"

projects[devel][version] = "1.26"

projects[diff][version] = "2.3"

projects[elements][version] = "1.2"

projects[emfield][version] = "2.5"

projects[features][version] = "1.2"

projects[ftools][version] = "1.3"

projects[filefield][version] = "3.10"

projects[globalredirect][version] = "1.4"

projects[imageapi][version] = "1.10"

projects[imagecache][version] = "2.0-beta12"

projects[imagefield][version] = "3.10"

projects[jquery_aop][version] = "1.0"

projects[jquery_ui][version] = "1.5"

projects[jquery_update][version] = "2.0-alpha1"

projects[less][version] = "2.7"

projects[libraries][version] = "1.0"

projects[link][version] = "2.9"

projects[media_flickr][version] = "1.12"

projects[media_youtube][version] = "1.3"

projects[modalframe][version] = "1.7"

projects[noderelationships][version] = "1.6"

projects[panels][version] = "3.10"

projects[panels_everywhere][version] = "1.x-dev"

projects[pathauto][version] = "1.6"

projects[pathologic][version] = "3.4"

projects[rules][version] = "1.4"

projects[strongarm][version] = "2.1"

projects[taxonomy_manager][version] = "2.2"

projects[token][version] = "1.18"

projects[views][version] = "2.16"

projects[views_customfield][version] = "1.0"

projects[views_or][version] = "1.0-alpha1"

projects[wysiwyg][version] = "2.4"

projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[zen][version] = "2.1"

projects[tinsel][version] = "1.1"

projects[tao][version] = "3.2"

projects[rubik][version] = "3.0-beta2"

;
; Modules using latest version with latest confirmed working installed version in comments
;
; Service links - 27 Mar 2012
projects[] = "service_links"

; Mobile codes = 7 Jun 2012
projects[] = "mobile_codes"


; Pull these from GitHub
; Themes
projects[behavenet.com][type] = "theme"
projects[behavenet.com][download][type] = "git"
projects[behavenet.com][download][url] = "git@github.com:mikeker/behavenet.com.git"
projects[behavenet.com][download][revision] = "9292f9475b43e3259bb988fc7f9d265058cc0258"
