<?php
$plugin = array(
  'title' => t('Behavenet default layout'),
  'theme' => 'behavenet_default',
  'icon' => 'behavenet_default.png',
  'css' => 'behavenet_default.css',
  'category' => 'Behavenet',
  'panels' => array(
    'header' => t('Header'),
    'main' => t('Main'),
    'main_callout' => t('Main area callout'),
    'left_sidebar' => t('Left sidebar'),
    'footer' => t('Footer'),
  ),
);
